Update codeql.yml

diff --git a/.github/workflows/codeql.yml b/.github/workflows/codeql.yml
--- a/.github/workflows/codeql.yml
+++ b/.github/workflows/codeql.yml
@@ -1,95 +1,47 @@
-# Para a maioria dos projetos, este arquivo de fluxo de trabalho não precisará ser alterado; você simplesmente precisa
-# enviá-lo ao seu repositório.
-#
-# Você pode desejar alterar este arquivo para substituir o conjunto de idiomas analisados,
-# ou para fornecer consultas personalizadas ou lógica de construção.
-#
-# ******** NOTA ********
-# Tentamos detectar os idiomas em seu repositório. Verifique
-# a matriz `language` definida abaixo para confirmar que você tem o conjunto correto de
-# idiomas CodeQL suportados.
-#
-name: "CodeQL Advanced"
-
-on:
-  push:
-    branches: [ "main" ]
-  pull_request:
-    branches: [ "main" ]
-    paths-ignore:
-       - '**/*.md'
-       - '**/*.txt' 
-  schedule:
-    - cron: '34 12 * * 2'
-
-jobs:
-  analyze:
-    name: Analyze (${{ matrix.language }})
-    # Runner size impacts CodeQL analysis time. To learn more, please see:
-    #   - https://gh.io/recommended-hardware-resources-for-running-codeql
-    #   - https://gh.io/supported-runners-and-hardware-resources
-    #   - https://gh.io/using-larger-runners (GitHub.com only)
-    # Consider using larger runners or machines with greater resources for possible analysis time improvements.
-    runs-on: ${{ (matrix.language == 'swift' && 'macos-latest') || 'ubuntu-latest' }}
-    permissions:
-      # required for all workflows
-      security-events: write
-
-      # required to fetch internal or private CodeQL packs
-      packages: read
-
-      # only required for workflows in private repositories
-      actions: read
-      contents: read
-
-    strategy:
-      fail-fast: false
-      matrix:
-        include:
-        - language: javascript-typescript
-          build-mode: none
-# CodeQL suporta os seguintes valores palavras-chave para 'language': 'c-cpp', 'csharp', 'go', 'java-kotlin', 'javascript-typescript', 'python', 'ruby', 'swift'
-# Use `c-cpp` para analisar código escrito em C, C++ ou ambos
-# Use 'java-kotlin' para analisar código escrito em Java, Kotlin ou ambos
-# Use 'javascript-typescript' para analisar código escrito em JavaScript, TypeScript ou ambos
-# Para saber mais sobre como alterar o linguagens que são analisadas ou personalizar o modo de construção para sua análise,
-# veja https://docs.github.com/en/code-security/code-scanning/creating-an-advanced-setup-for-code-scanning/customizing-your-advanced-setup-for-code-scanning.
-# Se você estiver analisando uma linguagem compilada, você pode modificar o 'build-mode' para essa linguagem para personalizar como
-# sua base de código é analisada, veja https://docs.github.com/en/code-security/code-scanning/creating-an-advanced-setup-for-code-scanning/codeql-code-scanning-for-compiled-languages
-    steps:
-    - name: Checkout repository
-      uses: actions/checkout@v4
-
-    # Initializes the CodeQL tools for scanning.
-    - name: Initialize CodeQL
-      uses: github/codeql-action/init@v3
-      with:
-        languages: ${{ matrix.language }}
-        build-mode: ${{ matrix.build-mode }}
-        # If you wish to specify custom queries, you can do so here or in a config file.
-        # By default, queries listed here will override any specified in a config file.
-        # Prefix the list here with "+" to use these queries and those in the config file.
-
-        # For more details on CodeQL's query packs, refer to: https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/configuring-code-scanning#using-queries-in-ql-packs
-        # queries: security-extended,security-and-quality
-
-    # If the analyze step fails for one of the languages you are analyzing with
-    # "We were unable to automatically build your code", modify the matrix above
-    # to set the build mode to "manual" for that language. Then modify this step
-    # to build your code.
-    # ℹ️ Command-line programs to run using the OS shell.
-    # 📚 See https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsrun
-    - if: matrix.build-mode == 'manual'
-      shell: bash
-      run: |
-        echo 'If you are using a "manual" build mode for one or more of the' \
-          'languages you are analyzing, replace this with the commands to build' \
-          'your code, for example:'
-        echo '  make bootstrap'
-        echo '  make release'
-        exit 1
-
-    - name: Perform CodeQL Analysis
-      uses: github/codeql-action/analyze@v3
-      with:
-        category: "/language:${{matrix.language}}"
+#name: "CodeQL Advanced"
+#on:
+#  push:
+#    branches: [ "main" ]
+#  pull_request:
+#    branches: [ "main" ]
+#    paths-ignore:
+#       - '**/*.md'
+#       - '**/*.txt' 
+#  schedule:
+#    - cron: '34 12 * * 2'
+#jobs:
+#  analyze:
+#    name: Analyze (${{ matrix.language }})
+#    runs-on: ${{ (matrix.language == 'swift' && 'macos-latest') || 'ubuntu-latest' }}
+#    permissions:
+#      security-events: write
+#      packages: read
+#      actions: read
+#      contents: read
+#    strategy:
+#      fail-fast: false
+#      matrix:
+#        include:
+#        - language: javascript-typescript
+#          build-mode: none
+#    steps:
+#    - name: Checkout repository
+#      uses: actions/checkout@v4
+#    - name: Initialize CodeQL
+#      uses: github/codeql-action/init@v3
+#      with:
+#        languages: ${{ matrix.language }}
+#        build-mode: ${{ matrix.build-mode }}
+#    - if: matrix.build-mode == 'manual'
+#      shell: bash
+#      run: |
+#        echo 'If you are using a "manual" build mode for one or more of the' \
+#          'languages you are analyzing, replace this with the commands to build' \
+#          'your code, for example:'
+#        echo '  make bootstrap'
+#        echo '  make release'
+#        exit 1
+#    - name: Perform CodeQL Analysis
+#      uses: github/codeql-action/analyze@v3
+#      with:
+#        category: "/language:${{matrix.language}}"
